// node ComputeRouter.test.cjs [path/to/typescript/lib/typescript.js]
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { transpile } = require('../../../../../../tests/harness.cjs');
const context = { exports: {}, Error, Map, Math, Number };
vm.runInNewContext(transpile(__dirname + '/ComputeRouter.ets'), context);
const { ScheduleNode, ComputeRouter, pickNode } = context.exports;
function node(partial) {
  const item = new ScheduleNode();
  Object.assign(item, partial);
  return item;
}
assert.equal(pickNode([]), null);
assert.equal(pickNode([node({ name: '空', model: '' })]), null, 'no model is not schedulable');
const idle = node({ name: '空闲', isSelf: true, model: 'Qwen', requests: 0, memAvail: 1000 });
const busy = node({ name: '忙', model: 'Qwen', requests: 2, memAvail: 9000 });
assert.equal(pickNode([busy, idle]).name, '空闲', 'idle preferred over busy even with less memory');
const self = node({ name: '本机', isSelf: true, model: 'Qwen', requests: 1, memAvail: 2000 });
const peer = node({ name: '对端', model: 'Qwen', requests: 1, memAvail: 8000 });
assert.equal(pickNode([self, peer]).name, '对端', 'same load prefers more memory');
assert.equal(pickNode([self, node({ name: '对端2', model: 'Qwen', requests: 1, memAvail: 2000 })]).isSelf, true,
  'equal load and memory prefers self');
assert.equal(pickNode([busy]).name, '忙', 'all busy still returns a modeled node');
const { pickRoute } = context.exports;
assert.equal(pickRoute([self, peer], 'auto', true).name, '对端', 'auto matches pickNode');
assert.equal(pickRoute([self, peer], 'pin1', false).isSelf, true, 'pin1 stays on the hub');
assert.equal(pickRoute([self, peer], 'pin2', true).name, '对端', 'pin2 stays on the other compute');
assert.equal(pickRoute([self, peer], 'split', true).isSelf, true, 'split can take the hub');
assert.equal(pickRoute([self, peer], 'split', false).name, '对端', 'split can take the peer');
assert.equal(pickRoute([peer], 'pin1', true), null, 'pin1 fails closed without the hub model');
assert.equal(pickRoute([self], 'pin2', false), null, 'pin2 fails closed without a peer');
const router = new ComputeRouter();
assert.equal(router.selfLoad(1), 1);
router.beginSelf();
assert.equal(router.selfLoad(0), 1, 'inflight covers a job before GEWU reports it');
assert.equal(router.selfLoad(1), 1, 'sampled job is the same inflight, not two');
router.endSelf();
assert.equal(router.selfLoad(1), 1);
assert.equal(router.selfLoad(0), 0);
const entry = { originEpoch: 1, originRequestId: 'r1', workerEpoch: 7, workerName: '算力B' };
router.beginDispatch('r1', entry);
assert.equal(router.workerLoad(7, 0), 1);
assert.equal(router.workerLoad(7, 1), 1, 'peer sample plus inflight is one job');
assert.equal(router.getDispatch('r1').workerName, '算力B');
assert.equal(router.finishDispatch('r1').originEpoch, 1);
assert.equal(router.workerLoad(7, 1), 1);
router.beginDispatch('a', { originEpoch: 1, originRequestId: 'a', workerEpoch: 8, workerName: 'A' });
router.beginDispatch('b', { originEpoch: 2, originRequestId: 'b', workerEpoch: 8, workerName: 'A' });
assert.equal(router.dropWorker(8).length, 2);
assert.equal(router.getDispatch('a'), undefined);
console.log('PASS: pickNode idle/memory/self, busy still scheduled, inflight dispatch accounting');
